version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
    steps:
      - checkout
      - run:
          name: Bundle Install
          command: bundle check -f fdk.gemspec || bundle install -f fdk.gemspec
      - run:
          name: Run tests
          command: |
            rake test

